# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.6"

[buildpack]
  description = "A Cloud Native Buildpack that contributes Spring Boot dependency information and slices an application into multiple layers"
  homepage = "https://github.com/paketo-buildpacks/spring-boot"
  id = "paketo-buildpacks/spring-boot"
  keywords = ["java", "spring", "spring-boot"]
  name = "Paketo Spring Boot Buildpack"
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/spring-boot/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml", "spring-generations.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "true"
    description = "whether to auto-configure Spring Boot environment properties from bindings"
    launch = true
    name = "BPL_SPRING_CLOUD_BINDINGS_ENABLED"

  [[metadata.dependencies]]
    id = "spring-cloud-bindings"
    name = "Spring Cloud Bindings"
    sha256 = "c75ef3152817c28c7049d7e0052dfba3ed461a7151984e594b656c0be927888e"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.8.0/spring-cloud-bindings-1.8.0.jar"
    version = "1.8.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/spring-cloud/spring-cloud-bindings/blob/main/LICENSE"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
